"""Bridge to the LBM wind tunnel: measured section polars, cached.

The fidelity ladder, and why it has three rungs rather than one:

  tier 0  VLM + flat-plate Cf     ~0.4 s   the search runs here
  tier 1  2D LBM section polar    ~1 min   the finalists' sections
  tier 2  3D LBM whole aircraft   hours    the winner, once

A D3Q19 run of a whole aeroplane is hours, and differential evolution
wants thousands of evaluations, so putting the tunnel in the loop would
buy one design per week. Instead the tunnel is spent where it changes a
decision: tier 0 ranks, tier 1 re-scores the top handful with real
viscous drag, tier 2 is the final check on the one you are going to
print. The ladder is the whole architecture.

What tier 1 replaces is the weakest number in tier 0. `DragModel` guesses
profile drag from a Prandtl-Schlichting flat plate with a form factor and
a roughness fudge -- defensible, and wrong by 20-40% on a 10% thick
section at Re 100k-400k where the boundary layer is transitional and the
printed surface is a helix of ridges. That is exactly the regime the 2D
solver was validated in (Phase 6, MH45 at Re 20k), and exactly the number
it can measure.

This module SHELLS OUT rather than importing the solver. The tunnel needs
CUDA and lives in its own repo with its own units discipline and its own
validation gates; importing it here would fork those rules. Writing a
scene file and running its entry point keeps one source of truth for the
physics -- and means the polars can be produced on the WSL/GPU side while
the search runs anywhere.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from ..geom.cst import Airfoil

DEFAULT_TUNNEL = Path.home() / "Desktop" / "windtunnel"


def section_key(af: Airfoil, re: float) -> str:
    """Content hash of the section and its Reynolds number.

    Coefficients, not a name: two sections with the same name and
    different coefficients are different aerofoils, and a cache that
    cannot tell them apart will serve the wrong polar silently."""
    blob = np.concatenate([af.au, af.al, [af.te_gap, af.te_camber, re]])
    return hashlib.sha256(blob.tobytes()).hexdigest()[:16]


@dataclass
class Polar:
    """Measured section data: alpha -> cl, cd, cm."""

    alpha_deg: np.ndarray
    cl: np.ndarray
    cd: np.ndarray
    cm: np.ndarray
    re: float
    source: str = "lbm"

    def cd_at(self, cl_target: float) -> float:
        """Profile drag at a given lift coefficient, by interpolation on
        the measured curve rather than on a fitted polynomial: the drag
        bucket of a reflexed section is not a parabola."""
        order = np.argsort(self.cl)
        return float(np.interp(cl_target, self.cl[order], self.cd[order]))

    @property
    def cl_max(self) -> float:
        return float(self.cl.max())

    def to_json(self) -> str:
        return json.dumps({"alpha": self.alpha_deg.tolist(),
                           "cl": self.cl.tolist(), "cd": self.cd.tolist(),
                           "cm": self.cm.tolist(), "re": self.re,
                           "source": self.source}, indent=1)

    @staticmethod
    def from_json(text: str) -> "Polar":
        d = json.loads(text)
        return Polar(np.array(d["alpha"]), np.array(d["cl"]),
                     np.array(d["cd"]), np.array(d["cm"]),
                     float(d["re"]), d.get("source", "lbm"))


def write_dat(af: Airfoil, path: Path, n: int = 160) -> Path:
    """Emit the section as a Selig .dat the tunnel's loader accepts."""
    path.parent.mkdir(parents=True, exist_ok=True)
    pts = af.coords(n)
    lines = [af.name] + [f"{x:.6f} {y:.6f}" for x, y in pts]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def scene_yaml(af: Airfoil, re: float, dat_rel: str, chord_cells: int = 320,
               name: str = "loft_section") -> str:
    """A tunnel scene in PHYSICAL units, the way that repo requires.

    Chord and viscosity are held at the tunnel's air values and the
    velocity is solved to hit the Reynolds number we actually fly at --
    matching Re, never raw speed, which is that project's first rule."""
    chord_m = 0.15
    nu = 1.5e-5
    v = re * nu / chord_m
    return f"""# generated by loft -- do not edit by hand
name: {name}
description: >
  loft section {af.name} at Re = {re:.0f}, alpha sweep.
  Chord {chord_m} m, velocity solved to match Re.

physical:
  char_length_m: {chord_m}
  velocity_ms: {v:.4f}
  nu_m2s: {nu}

lattice:
  cells_per_char: {chord_cells}
  u_lat: 0.05

domain:
  length_chars: 8
  height_chars: 5

sgs: true

boundaries:
  inlet: equilibrium_ramp
  outlet: anechoic_sponge
  top_bottom: periodic
  ramp_steps: 2000
  sponge_fraction: 0.08

obstacle:
  type: airfoil_dat
  dat_file: {dat_rel}
  alpha_deg: 0.0
  center_x_chars: 2.0
  center_y_chars: 2.5
  edge_supersample: 4
"""


def measure(
    af: Airfoil,
    re: float,
    alphas=(-2.0, 0.0, 2.0, 4.0, 6.0, 8.0),
    tunnel_dir: Path = DEFAULT_TUNNEL,
    cache_dir: Path | None = None,
    python: str | None = None,
    timeout_s: int = 7200,
) -> Polar:
    """Run (or read from cache) an LBM alpha sweep for one section.

    Cached by content hash, because the search will ask for the same
    section many times and a tunnel run is minutes. A cache hit is the
    normal case; a miss is a deliberate spend."""
    cache_dir = Path(cache_dir or (Path(__file__).resolve().parents[2] / "cache" / "polars"))
    cache_dir.mkdir(parents=True, exist_ok=True)
    key = section_key(af, re)
    hit = cache_dir / f"{key}.json"
    if hit.exists():
        return Polar.from_json(hit.read_text(encoding="utf-8"))

    tunnel_dir = Path(tunnel_dir)
    if not (tunnel_dir / "run.py").exists():
        raise FileNotFoundError(
            f"no wind tunnel at {tunnel_dir} (expected run.py). "
            f"Pass tunnel_dir=... or stay on tier 0.")

    dat = write_dat(af, tunnel_dir / "assets" / f"pf_{key}.dat")
    scene = tunnel_dir / "scenes" / f"pf_{key}.yaml"
    scene.write_text(scene_yaml(af, re, f"assets/{dat.name}",
                                name=f"pf_{key}"), encoding="utf-8")

    rows = []
    for al in alphas:
        cmd = [python or sys.executable, "run.py", "--scene", f"pf_{key}",
               "--seed", "0", "--measure-force", "--alpha", str(al)]
        proc = subprocess.run(cmd, cwd=tunnel_dir, capture_output=True,
                              text=True, timeout=timeout_s)
        if proc.returncode != 0:
            raise RuntimeError(f"tunnel failed at alpha={al}:\n{proc.stderr[-2000:]}")
        rows.append((al, *_parse_force(proc.stdout)))

    rows = np.array(rows, dtype=float)
    polar = Polar(rows[:, 0], rows[:, 1], rows[:, 2], rows[:, 3], re, "lbm-2d")
    hit.write_text(polar.to_json(), encoding="utf-8")
    return polar


def _parse_force(stdout: str) -> tuple[float, float, float]:
    """Pull cl/cd/cm out of the tunnel's --measure-force report.

    Deliberately strict: a silent zero here would look like a
    miraculously low-drag aerofoil and win the optimization."""
    vals: dict[str, float] = {}
    for line in stdout.splitlines():
        low = line.lower().replace("=", " ").replace(":", " ")
        parts = low.split()
        for i, tok in enumerate(parts[:-1]):
            if tok in ("cl", "cd", "cm") and tok not in vals:
                try:
                    vals[tok] = float(parts[i + 1])
                except ValueError:
                    pass
    missing = {"cl", "cd"} - vals.keys()
    if missing:
        raise RuntimeError(
            f"could not parse {sorted(missing)} from the tunnel output; "
            f"last 500 chars:\n{stdout[-500:]}")
    return vals["cl"], vals["cd"], vals.get("cm", 0.0)


class MeasuredDrag:
    """Tier-1 drag model: strip theory on measured section polars.

    Drop-in for DragModel. Where a strip's Reynolds number or section
    falls outside what has been measured, it says so instead of
    extrapolating -- an optimizer handed a confidently wrong low drag
    will walk straight to it."""

    def __init__(self, polars: dict[str, Polar], fallback=None):
        self.polars = polars
        self.fallback = fallback
        self.misses = 0

    def cd0(self, plan, v_ms: float, n: int = 20) -> float:
        from .performance import NU_AIR
        e = np.linspace(0.0, 1.0, n)
        y = e * plan.half_span_m
        vals = []
        for v in e:
            st = plan.at(float(v))
            re = st.chord_m * v_ms / NU_AIR
            key = section_key(st.airfoil, re)
            p = self.polars.get(key)
            if p is None:
                self.misses += 1
                if self.fallback is None:
                    raise KeyError(f"no measured polar for strip eta={v:.2f}")
                vals.append(None)
            else:
                vals.append(p.cd_at(0.3) * st.chord_m)
        if any(x is None for x in vals):
            return self.fallback.cd0(plan, v_ms, n)
        return float(2.0 * np.trapezoid(np.array(vals), y) / plan.area_m2)
