#!/usr/bin/env python3
"""Drive windtunnel-sim over a section: polar sweep + beauty video runs.

Run this from the loft repo; it writes scenes and assets INTO the
windtunnel repo and shells out to its entry point, because that project
owns its own units discipline and validation gates and importing its
solver here would fork them.

    python scripts/tunnel_sweep.py --design out/trainer/design.json \
        --alphas -2,0,2,4,6,8,10,12,14 --chord-cells 240

What it measures is precisely what the VLM cannot: viscous drag and
STALL. The lattice is inviscid, so it reports a lift curve that rises
for ever and a profile drag with no alpha dependence at all -- which is
why the optimizer was never charged for trimming at 9 degrees. A measured
polar is the correction.
"""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from loft.geom import cst                                    # noqa: E402
from loft.search.design import Mission, build                # noqa: E402

WIN_TUNNEL = Path.home() / "Desktop" / "windtunnel"
WSL_TUNNEL = "/mnt/c/Users/aipla/Desktop/windtunnel"
WSL_PY = "~/wt-venv/bin/python"
NU_AIR = 1.5e-5


def wsl(cmd: str, timeout: int = 14400) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["wsl", "-d", "Ubuntu", "-e", "bash", "-lc", cmd],
        capture_output=True, text=True, timeout=timeout)


def write_dat(af, path: Path, n: int = 160) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    pts = af.coords(n)
    path.write_text("\n".join([af.name.replace("\n", " ")[:60]]
                              + [f"{x:.6f} {y:.6f}" for x, y in pts]) + "\n",
                    encoding="utf-8")
    return path


def scene_text(name: str, dat_rel: str, re: float, alpha: float,
               chord_cells: int, u_lat: float = 0.05,
               chord_m: float = 0.15) -> str:
    v = re * NU_AIR / chord_m
    tau = 3.0 * u_lat * chord_cells / re + 0.5
    if tau < 0.501:
        raise SystemExit(
            f"tau = {tau:.5f} is below the SGS floor: raise cells or u_lat. "
            f"Re={re:.0f} cells={chord_cells} u_lat={u_lat}")
    return f"""# generated by loft/scripts/tunnel_sweep.py -- do not hand edit
name: {name}
description: >
  loft section at Re = {re:.0f}, alpha = {alpha:g} deg.
  Chord {chord_m} m; velocity solved to match Re (never matched on raw speed).

physical:
  char_length_m: {chord_m}
  velocity_ms: {v:.4f}
  nu_m2s: {NU_AIR}

lattice:
  cells_per_char: {chord_cells}
  u_lat: {u_lat}

domain:
  length_chars: 8
  height_chars: 5

sgs: true

boundaries:
  inlet: equilibrium_ramp
  outlet: anechoic_sponge
  top_bottom: periodic
  ramp_steps: 2000
  sponge_fraction: 0.08

obstacle:
  type: airfoil_dat
  dat_file: {dat_rel}
  alpha_deg: {alpha:g}
  center_x_chars: 2.0
  center_y_chars: 2.5
  edge_supersample: 4
"""


def parse_forces(stdout: str) -> tuple[float, float]:
    for line in stdout.splitlines():
        if "Cl =" in line and "Cd =" in line:
            parts = line.replace("=", " ").replace("±", " ").split()
            cl = float(parts[parts.index("Cl") + 1])
            cd = float(parts[parts.index("Cd") + 1])
            return cl, cd
    raise RuntimeError("no force line in tunnel output:\n" + stdout[-800:])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--design", type=Path, default=None)
    ap.add_argument("--airfoil", type=Path, default=ROOT / "assets" / "mh45.dat")
    ap.add_argument("--mission", default="trainer")
    ap.add_argument("--alphas", default="-2,0,2,4,6,8,10,12,14")
    ap.add_argument("--re", type=float, default=6.0e4,
                    help="60k is the trainer OUTER panel at 9 m/s -- where "
                         "the tip-stall gate lives")
    ap.add_argument("--chord-cells", type=int, default=340, dest="chord_cells")
    ap.add_argument("--u-lat", type=float, default=0.07, dest="u_lat")
    ap.add_argument("--conv-times", type=float, default=26.0, dest="conv")
    ap.add_argument("--tag", default="pf")
    ap.add_argument("--video-alphas", default="4,10", dest="video_alphas")
    ap.add_argument("--video-steps", type=int, default=90000, dest="video_steps")
    ap.add_argument("--presets", default="speed,dye",
                    help="video presets to render. streaklines is ~110 MB a "
                         "clip and the least diagnostic; vorticity is pretty "
                         "but speed+dye show the same separation more "
                         "legibly and at a twentieth of the size.")
    ap.add_argument("--out", type=Path, default=ROOT / "out" / "tunnel")
    ap.add_argument("--skip-polar", action="store_true")
    ap.add_argument("--jobs", type=int, default=3,
                    help="concurrent tunnel runs; one does not "
                         "saturate the GPU")
    a = ap.parse_args()

    a.out.mkdir(parents=True, exist_ok=True)
    base = cst.load_selig(a.airfoil)
    if a.design:
        d = json.loads(a.design.read_text())
        mission = (Mission.beginner_trainer() if a.mission == "trainer"
                   else Mission.fpv_1m())
        plan = build(np.array(d["u"]), mission, base)
        section = plan.at(0.5).airfoil          # the mid-span working section
        label = "trainer mid-span section"
    else:
        section, label = base, base.name

    dat = write_dat(section, WIN_TUNNEL / "assets" / f"{a.tag}_section.dat")
    print(f"section: {label}\n  t/c {section.t_max:.4f}  camber "
          f"{section.camber_max:.4f}  te_camber {section.te_camber:+.5f}")
    print(f"  wrote {dat}")

    alphas = [float(x) for x in a.alphas.split(",")]
    steps = int(a.conv * a.chord_cells / a.u_lat)
    print(f"  Re {a.re:.0f}, chord {a.chord_cells} cells, {steps} steps "
          f"per alpha ({a.conv:g} convective times)\n")

    rows = []
    if not a.skip_polar:
        # Run several angles CONCURRENTLY. One 4.6 Mcell D2Q9 run leaves
        # the GPU at 10-30%: the grid is too small to saturate a 5080 and
        # per-step launch overhead dominates. Three runs share the card
        # almost perfectly and turn a 4.7 hour sweep into about 1.6.
        # Memory is the limit, not compute -- roughly 4 GB each.
        def one(al: float):
            name = f"{a.tag}_a{al:g}".replace("-", "m").replace(".", "p")
            (WIN_TUNNEL / "scenes" / f"{name}.yaml").write_text(
                scene_text(name, f"assets/{dat.name}", a.re, al,
                           a.chord_cells, a.u_lat),
                encoding="utf-8")
            cmd = (f"cd {WSL_TUNNEL} && {WSL_PY} run.py --scene {name} "
                   f"--seed 0 --steps {steps} --measure-force --solver fused "
                   f"--out /tmp/{name}")
            proc = wsl(cmd)
            if proc.returncode != 0:
                return al, None, None, proc.stderr[-500:]
            try:
                cl, cd = parse_forces(proc.stdout)
            except RuntimeError as e:
                return al, None, None, str(e)[:300]
            return al, cl, cd, None

        with ThreadPoolExecutor(max_workers=a.jobs) as pool:
            for al, cl, cd, err in pool.map(one, alphas):
                if err:
                    print(f"  alpha {al:+5.1f}  FAILED: {err}", flush=True)
                    continue
                rows.append({"alpha": al, "cl": cl, "cd": cd,
                             "ld": cl / cd if cd else 0.0})
                print(f"  alpha {al:+5.1f}  Cl {cl:+.4f}  Cd {cd:.5f}  "
                      f"L/D {cl / cd if cd else 0:+6.2f}", flush=True)

        rows.sort(key=lambda r: r["alpha"])
        with (a.out / "polar.csv").open("w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=["alpha", "cl", "cd", "ld"])
            w.writeheader()
            w.writerows(rows)
        print(f"\npolar -> {a.out / 'polar.csv'}")

    for al in [float(x) for x in a.video_alphas.split(",") if x.strip()]:
        name = f"{a.tag}_vid_a{al:g}".replace("-", "m").replace(".", "p")
        (WIN_TUNNEL / "scenes" / f"{name}.yaml").write_text(
            scene_text(name, f"assets/{dat.name}", a.re, al,
                       a.chord_cells, a.u_lat),
            encoding="utf-8")
        every = max(a.video_steps // 400, 1)
        # --all-presets writes frames to <out>/<preset>/frames, NOT to
        # <out>/frames, so make_video.py has to be pointed at each preset
        # directory in turn. Pointing it at the run directory finds
        # nothing, says "no frames", and exits 0 -- which looked like a
        # failed simulation when in fact 1604 rendered PNGs were sitting
        # on disk the whole time.
        presets = tuple(x.strip() for x in a.presets.split(",") if x.strip())
        cmd = (f"cd {WSL_TUNNEL} && {WSL_PY} run.py --scene {name} --seed 0 "
               f"--steps {a.video_steps} --solver fused --all-presets "
               f"--frame-every {every} --out /tmp/{name}")
        print(f"\n  video alpha {al:+g} ({a.video_steps} steps) ...",
              flush=True)
        proc = wsl(cmd)
        if proc.returncode != 0:
            print(proc.stderr[-900:])
            continue
        for preset in presets:
            wsl(f"cd {WSL_TUNNEL} && {WSL_PY} scripts/make_video.py "
                f"/tmp/{name}/{preset} 2>&1 | tail -1")
        tag = f"a{al:g}".replace("-", "m").replace(".", "p")
        got = wsl(" ; ".join(
            f"cp /tmp/{name}/{p}/{p}.mp4 "
            f"/mnt/c/Users/aipla/Desktop/loft/out/tunnel/{tag}_{p}.mp4"
            for p in presets) + " ; ls -la /mnt/c/Users/aipla/Desktop/"
            f"loft/out/tunnel/{tag}_*.mp4 | wc -l")
        print(got.stdout.strip() or got.stderr.strip())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
